name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v3
    - name: Clone source repo
      run: git clone https://github.com/Azure-Samples/dotNET-FrontEnd-to-BackEnd-on-Azure-Container-Apps
    - run: ls -l
  # Build storage image
    - name: Build the store image
      run: docker build src/store --file Dockerfile --tag store:latest
